enum SettingsErrorCodes {
  initSettings,
  makeListeners,
  startListening,
  cancelWorkerListening,
  resumeListening,
  setupPreviewBuisnesses,
  addPreviewBuisness,
  removePreviewBuisness,
  emptyBuisnessData,
  loadBuisness,
  loadLastBuisness,
  updateLastBuisness,
  deleteChangingImage,
  deleteStoryImage,
  uploadChangingImages,
  uploadStoryImages,
  addOrRemoveLikeForStoryImage,
  cacheImages,
  cacheStoryImages,
  updateShopIcon,
  deleteShopIcon,
  updateShopName,
  updateShopPhone,
  updateAddress,
  updateInstagramAccount,
  addUpdate,
  replaceUpdate,
  deleteUpdate,
  removeWorker,
  addWorker,
  uploadNewShopIcon,
  saveProduct,
  deleteProduct,
  changeChangingImagesSwapSeconds,
  updateManagerFcmIfNeeded,
  updateCurrency,
  updateNotifyOnNewCustomerIfNeeded,
  updateBusinessType
}

Map<SettingsErrorCodes, int> settingsCodeToInt = {
  SettingsErrorCodes.initSettings: 1001,
  SettingsErrorCodes.startListening: 1004,
  SettingsErrorCodes.cancelWorkerListening: 1005,
  SettingsErrorCodes.resumeListening: 1006,
  SettingsErrorCodes.setupPreviewBuisnesses: 1007,
  SettingsErrorCodes.addPreviewBuisness: 1008,
  SettingsErrorCodes.removePreviewBuisness: 1009,
  SettingsErrorCodes.emptyBuisnessData: 1010,
  SettingsErrorCodes.loadBuisness: 1011,
  SettingsErrorCodes.loadLastBuisness: 1012,
  SettingsErrorCodes.updateLastBuisness: 1013,
  SettingsErrorCodes.deleteChangingImage: 1014,
  SettingsErrorCodes.deleteStoryImage: 1015,
  SettingsErrorCodes.uploadChangingImages: 1016,
  SettingsErrorCodes.uploadStoryImages: 1017,
  SettingsErrorCodes.addOrRemoveLikeForStoryImage: 1018,
  SettingsErrorCodes.cacheImages: 1019,
  SettingsErrorCodes.cacheStoryImages: 1020,
  SettingsErrorCodes.updateShopIcon: 1021,
  SettingsErrorCodes.deleteShopIcon: 1022,
  SettingsErrorCodes.updateShopName: 1023,
  SettingsErrorCodes.updateShopPhone: 1024,
  SettingsErrorCodes.updateAddress: 1025,
  SettingsErrorCodes.updateInstagramAccount: 1026,
  SettingsErrorCodes.addUpdate: 1027,
  SettingsErrorCodes.replaceUpdate: 1028,
  SettingsErrorCodes.deleteUpdate: 1029,
  SettingsErrorCodes.removeWorker: 1030,
  SettingsErrorCodes.addWorker: 1031,
  SettingsErrorCodes.uploadNewShopIcon: 1032,
  SettingsErrorCodes.saveProduct: 1033,
  SettingsErrorCodes.deleteProduct: 1034,
  SettingsErrorCodes.changeChangingImagesSwapSeconds: 1035,
  SettingsErrorCodes.updateManagerFcmIfNeeded: 1036,
  SettingsErrorCodes.updateCurrency: 1037,
  SettingsErrorCodes.updateNotifyOnNewCustomerIfNeeded: 1038,
  SettingsErrorCodes.updateBusinessType: 1039
};
