enum UserErrorCodes {
  createUser,
  deleteUser,
  isConnected,
  logout,
  deviceTurnOffNotifications,
  deviceTurnOnNotifications,
  subToNotification,
  unSubNotification,
  isAlreadySub,
  pauseListening,
  cancelListening,
  resumeListening,
  addOrRemoveLikeForStoryImage,
  setupUser,
  notifyCanceledBooking,
  removeExpiredSubNotifications,
  removeDeletedBuisnessesSubNotifications,
  cleanExpiredData,
  replaceVisitedBuisness,
  addVisitedBuisness,
  deleteVisitedBuisness,
  removeDeletedLastVisitedBuisnesses,
  addBooking,
  needToHoldOn,
  deleteBookingOnlyFromUserDoc,
  deleteBooking,
  updateBooking,
  getPermission,
  setGender,
  setName,
  updateUserName,
  notifyLimited,
  isConnectedAnonymously,
  setupAnonymousUser,
  anonymousAllSetup,
  updateAnonymousInfo,
  updateFcmIfNeeded,
  updateActiveEntitlementsIdIfNeeded
}

Map<UserErrorCodes, int> userCodeToInt = {
  UserErrorCodes.createUser: 1,
  UserErrorCodes.deleteUser: 2,
  UserErrorCodes.isConnected: 3,
  UserErrorCodes.logout: 4,
  UserErrorCodes.deviceTurnOffNotifications: 5,
  UserErrorCodes.deviceTurnOnNotifications: 6,
  UserErrorCodes.subToNotification: 7,
  UserErrorCodes.unSubNotification: 8,
  UserErrorCodes.isAlreadySub: 9,
  UserErrorCodes.pauseListening: 10,
  UserErrorCodes.cancelListening: 11,
  UserErrorCodes.resumeListening: 12,
  UserErrorCodes.setupUser: 13,
  UserErrorCodes.notifyCanceledBooking: 14,
  UserErrorCodes.removeExpiredSubNotifications: 15,
  UserErrorCodes.removeDeletedBuisnessesSubNotifications: 16,
  UserErrorCodes.cleanExpiredData: 17,
  UserErrorCodes.replaceVisitedBuisness: 18,
  UserErrorCodes.addVisitedBuisness: 19,
  UserErrorCodes.deleteVisitedBuisness: 20,
  UserErrorCodes.removeDeletedLastVisitedBuisnesses: 21,
  UserErrorCodes.addBooking: 21,
  UserErrorCodes.needToHoldOn: 22,
  UserErrorCodes.deleteBookingOnlyFromUserDoc: 23,
  UserErrorCodes.deleteBooking: 24,
  UserErrorCodes.updateBooking: 25,
  UserErrorCodes.getPermission: 26,
  UserErrorCodes.setGender: 27,
  UserErrorCodes.setName: 28,
  UserErrorCodes.updateUserName: 29,
  UserErrorCodes.notifyLimited: 30,
  UserErrorCodes.isConnectedAnonymously: 31,
  UserErrorCodes.setupAnonymousUser: 32,
  UserErrorCodes.anonymousAllSetup: 33,
  UserErrorCodes.updateAnonymousInfo: 34,
  UserErrorCodes.updateFcmIfNeeded: 35,
  UserErrorCodes.updateActiveEntitlementsIdIfNeeded: 36,
  UserErrorCodes.addOrRemoveLikeForStoryImage: 37
};
