// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSIQHCC23Z7ul639fD8JLMHu4yN77_0VA',
    appId: '1:670820779934:web:fdcf77a952b59c3090788f',
    messagingSenderId: '670820779934',
    projectId: 'managementsystemapp-c1fda',
    authDomain: 'managementsystemapp-c1fda.firebaseapp.com',
    databaseURL: 'https://managementsystemapp-c1fda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'managementsystemapp-c1fda.appspot.com',
    measurementId: 'G-WP8J044JN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOtuLpmBpMDgHYNZbgHQrBDaDXkXqGbjI',
    appId: '1:670820779934:android:04b6e84306cac46a90788f',
    messagingSenderId: '670820779934',
    projectId: 'managementsystemapp-c1fda',
    databaseURL: 'https://managementsystemapp-c1fda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'managementsystemapp-c1fda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1WWMTbbU-bm1OAYIyPrmuUijWALJClks',
    appId: '1:670820779934:ios:a57884e2212a4ff990788f',
    messagingSenderId: '670820779934',
    projectId: 'managementsystemapp-c1fda',
    databaseURL: 'https://managementsystemapp-c1fda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'managementsystemapp-c1fda.appspot.com',
    androidClientId: '670820779934-5uq9ucnhk9stpj8ue605lstjjqkodqjq.apps.googleusercontent.com',
    iosClientId: '670820779934-d8u4k9tqfa9efclnsap39n5a8capcnfp.apps.googleusercontent.com',
    iosBundleId: 'com.simplecode.managementSystemApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1WWMTbbU-bm1OAYIyPrmuUijWALJClks',
    appId: '1:670820779934:ios:6643417c5a9295a890788f',
    messagingSenderId: '670820779934',
    projectId: 'managementsystemapp-c1fda',
    databaseURL: 'https://managementsystemapp-c1fda-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'managementsystemapp-c1fda.appspot.com',
    androidClientId: '670820779934-5uq9ucnhk9stpj8ue605lstjjqkodqjq.apps.googleusercontent.com',
    iosClientId: '670820779934-m2jfrm9kjjjtrio3n3ol5jkpt2m6ghkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.managementSystemApp',
  );
}
