enum BusinessesTypes {
  barber,
  polish,
  beautician,
  manicurePedicure,
  eyelashes,
  eyebrows,
  braids,
  makeUpArtist,
  tattooArtist,
  hairRemoval,
  masseur,
  physiotherapy,
  cobblers,
  clown,
  socialWorker,
  magician,
  doctor,
  veterinarian,
  communicationTherapist,
  dogGroomer,
  psychologist,
  Tutor,
  weddingDresses,
  danceTeacher,
  babysitter,
  reflexologist,
  dietitian,
  carWash,
  photographer,
  swimmingTeacher,
  counselor,
  mentor,
  tennisCoach,
  privateChef,
  personalTrainer,
  lawyer,
  sales,
  realEstate,
  drivingTeacher,
  investmentAdvice,
  library,
  other,
}

const Map<BusinessesTypes, String> businessTypeToStr = {
  BusinessesTypes.barber: "barber",
  BusinessesTypes.polish: "polish",
  BusinessesTypes.beautician: "beautician",
  BusinessesTypes.manicurePedicure: "manicurePedicure",
  BusinessesTypes.eyelashes: "eyelashes",
  BusinessesTypes.eyebrows: "eyebrows",
  BusinessesTypes.babysitter: "babysitter",
  BusinessesTypes.braids: "braids",
  BusinessesTypes.makeUpArtist: "makeUpArtist",
  BusinessesTypes.tattooArtist: "tattooArtist",
  BusinessesTypes.hairRemoval: "hairRemoval",
  BusinessesTypes.masseur: "masseur",
  BusinessesTypes.cobblers: "cobblers",
  BusinessesTypes.clown: "clown",
  BusinessesTypes.socialWorker: "socialWorker",
  BusinessesTypes.magician: "magician",
  BusinessesTypes.doctor: "doctor",
  BusinessesTypes.veterinarian: "veterinarian",
  BusinessesTypes.communicationTherapist: "communicationTherapist",
  BusinessesTypes.dogGroomer: "dogGroomer",
  BusinessesTypes.psychologist: "psychologist",
  BusinessesTypes.physiotherapy: "physiotherapy",
  BusinessesTypes.Tutor: "Tutor",
  BusinessesTypes.weddingDresses: "weddingDresses",
  BusinessesTypes.danceTeacher: "danceTeacher",
  BusinessesTypes.reflexologist: "reflexologist",
  BusinessesTypes.dietitian: "dietitian",
  BusinessesTypes.carWash: "carWash",
  BusinessesTypes.photographer: "photographer",
  BusinessesTypes.swimmingTeacher: "swimmingTeacher",
  BusinessesTypes.counselor: "counselor",
  BusinessesTypes.mentor: "mentor",
  BusinessesTypes.tennisCoach: "tennisCoach",
  BusinessesTypes.privateChef: "privateChef",
  BusinessesTypes.personalTrainer: "personalTrainer",
  BusinessesTypes.lawyer: "lawyer",
  BusinessesTypes.sales: "sales",
  BusinessesTypes.realEstate: "realEstate",
  BusinessesTypes.drivingTeacher: "drivingTeacher",
  BusinessesTypes.investmentAdvice: "investmentAdvice",
  BusinessesTypes.library: "library",
  BusinessesTypes.other: "other",
};

const Map<BusinessesTypes, String> businessTypesToIcon = {
  BusinessesTypes.barber: "assets/icons/barber.webp",
  BusinessesTypes.polish: "assets/icons/nail-polish.webp",
  BusinessesTypes.other: "assets/icons/more-information.webp",
  BusinessesTypes.beautician: "assets/icons/hairdresser.webp",
  BusinessesTypes.manicurePedicure: "assets/icons/finger-with-nail.webp",
  BusinessesTypes.babysitter: "assets/icons/mother.webp",
  BusinessesTypes.eyelashes: "assets/icons/eye.webp",
  BusinessesTypes.eyebrows: "assets/icons/liner.webp",
  BusinessesTypes.braids: "assets/icons/wig.webp",
  BusinessesTypes.makeUpArtist: "assets/icons/make-up.webp",
  BusinessesTypes.tattooArtist: "assets/icons/tattoo.webp",
  BusinessesTypes.hairRemoval: "assets/icons/hair-removal.webp",
  BusinessesTypes.masseur: "assets/icons/masseur.webp",
  BusinessesTypes.cobblers: "assets/icons/cobbler.webp",
  BusinessesTypes.clown: "assets/icons/clown.webp",
  BusinessesTypes.socialWorker: "assets/icons/social-care.webp",
  BusinessesTypes.magician: "assets/icons/hat.webp",
  BusinessesTypes.physiotherapy: "assets/icons/physical-therapy.webp",
  BusinessesTypes.doctor: "assets/icons/stethoscope.webp",
  BusinessesTypes.veterinarian: "assets/icons/veterinarian.webp",
  BusinessesTypes.communicationTherapist: "assets/icons/communication.webp",
  BusinessesTypes.dogGroomer: "assets/icons/groomer.webp",
  BusinessesTypes.psychologist: "assets/icons/psychologist.webp",
  BusinessesTypes.Tutor: "assets/icons/teacher.webp",
  BusinessesTypes.weddingDresses: "assets/icons/wedding-dress.webp",
  BusinessesTypes.danceTeacher: "assets/icons/dancing.webp",
  BusinessesTypes.reflexologist: "assets/icons/knee.webp",
  BusinessesTypes.dietitian: "assets/icons/diet.webp",
  BusinessesTypes.carWash: "assets/icons/car-wash.webp",
  BusinessesTypes.photographer: "assets/icons/photographer.webp",
  BusinessesTypes.swimmingTeacher: "assets/icons/swimming.webp",
  BusinessesTypes.counselor: "assets/icons/discussion.webp",
  BusinessesTypes.mentor: "assets/icons/leadership.webp",
  BusinessesTypes.tennisCoach: "assets/icons/coach.webp",
  BusinessesTypes.privateChef: "assets/icons/chef.webp",
  BusinessesTypes.personalTrainer: "assets/icons/fitness.webp",
  BusinessesTypes.lawyer: "assets/icons/lawyer.webp",
  BusinessesTypes.sales: "assets/icons/sales.webp",
  BusinessesTypes.realEstate: "assets/icons/real-estate.webp",
  BusinessesTypes.drivingTeacher: "assets/icons/steering-wheel.webp",
  BusinessesTypes.investmentAdvice: "assets/icons/financial-profit.webp",
  BusinessesTypes.library: "assets/icons/book.webp",
};

const Map<String, BusinessesTypes> businessTypeFromStr = {
  "barber": BusinessesTypes.barber,
  "polish": BusinessesTypes.polish,
  "beautician": BusinessesTypes.beautician,
  "manicurePedicure": BusinessesTypes.manicurePedicure,
  "eyelashes": BusinessesTypes.eyelashes,
  "eyebrows": BusinessesTypes.eyebrows,
  "babysitter": BusinessesTypes.babysitter,
  "braids": BusinessesTypes.braids,
  "makeUpArtist": BusinessesTypes.makeUpArtist,
  "tattooArtist": BusinessesTypes.tattooArtist,
  "hairRemoval": BusinessesTypes.hairRemoval,
  "masseur": BusinessesTypes.masseur,
  "cobblers": BusinessesTypes.cobblers,
  "clown": BusinessesTypes.clown,
  "socialWorker": BusinessesTypes.socialWorker,
  "magician": BusinessesTypes.magician,
  "doctor": BusinessesTypes.doctor,
  "veterinarian": BusinessesTypes.veterinarian,
  "communicationTherapist": BusinessesTypes.communicationTherapist,
  "dogGroomer": BusinessesTypes.dogGroomer,
  "psychologist": BusinessesTypes.psychologist,
  "physiotherapy": BusinessesTypes.physiotherapy,
  "Tutor": BusinessesTypes.Tutor,
  "weddingDresses": BusinessesTypes.weddingDresses,
  "danceTeacher": BusinessesTypes.danceTeacher,
  "reflexologist": BusinessesTypes.reflexologist,
  "dietitian": BusinessesTypes.dietitian,
  "carWash": BusinessesTypes.carWash,
  "photographer": BusinessesTypes.photographer,
  "swimmingTeacher": BusinessesTypes.swimmingTeacher,
  "counselor": BusinessesTypes.counselor,
  "mentor": BusinessesTypes.mentor,
  "tennisCoach": BusinessesTypes.tennisCoach,
  "privateChef": BusinessesTypes.privateChef,
  "personalTrainer": BusinessesTypes.personalTrainer,
  "lawyer": BusinessesTypes.lawyer,
  "sales": BusinessesTypes.sales,
  "realEstate": BusinessesTypes.realEstate,
  "drivingTeacher": BusinessesTypes.drivingTeacher,
  "investmentAdvice": BusinessesTypes.investmentAdvice,
  "library": BusinessesTypes.library,
  "other": BusinessesTypes.other,
};
