/// Thes file is saving the const vars of the "rapyd" P2p service
/// example: the supported countries in each area

const Map<String, Set<String>> rapydSupportedCountries = {
  'Americas': {
    "Brazil",
    "Canada",
    "Chile",
    "Colombia",
    "Dominican Republic",
    "El Salvador",
    "Mexico",
    "Peru",
    "Portugal",
    "United States of America (USA)",
    "Virgin Islands (US)"
  },
  "Europe and the Middle East": {
    "Andorra",
    "Austria",
    "Belgium",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Georgia",
    "Germany",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Hungary",
    "Iceland",
    "Ireland",
    "Israel",
    "Italy",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Malta",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Netherlands",
    "Northern Ireland",
    "Norway",
    "Poland",
    "Romania",
    "Russian Federation",
    "San Marino",
    "Slovak Republic (Slovakia)",
    "Slovenia",
    "South Africa",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "United Kingdom",
    "Vatican"
  },
  "Asia Pacific": {
    "Australia",
    "Hong Kong",
    "India",
    "Indonesia",
    "Japan",
    "Malaysia",
    "New Zealand",
    "Philippines",
    "Singapore",
    "South Korea",
    "Taiwan",
    "Thailand",
    "Vietnam"
  }
};
